// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

// ClerkProvider is client-side, so we’ll import a wrapper component instead:
import ClerkProviderWrapper from "@/components/ClerkProviderWrapper";
import ThemeProviderWrapper from "@/components/ThemeProviderWrapper";

export const metadata: Metadata = {
  title: "NATURE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Wrap client providers in their own components */}
        <ClerkProviderWrapper>
          <ThemeProviderWrapper>{children}</ThemeProviderWrapper>
        </ClerkProviderWrapper>
      </body>
    </html>
  );
}
