
export const events = [
  {
    id: 1,
    title: "Manchu picchu & secrete valley",
    slug: "manchu-picchu-secrete-valley",
    country: "peru",
    category: "most popular",
    duration: 9,
    groupSize: "8-12 people",
    image: "/image copy 4.png",
    tags: ["sunrise", "thelect", "good vibes"],
    price: 650,
    discountPrice: 250,
    monthly: 110,
    rate: 6.4,
    reviews: 1600,
    quantity: 1,
  },
  {
    id: 2,
    title: "Machu Picchu & Sacred Valley",
    slug: "machu-picchu-sacred-valley",
    country: "Peru",
    category: "most popular",
    duration: 7,
    groupSize: "8-12 people",
    image: "/image copy 2.png",
    tags: ["sunrise", "adventure", "nature"],
    price: 550,
    discountPrice: 200,
    monthly: 99,
    rate: 4.6,
    reviews: 1400,
    quantity: 1,
  },
  {
    id: 3,
    title: "Safari in the Serengeti",
    slug: "safari-in-the-serengeti",
    country: "Tanzania",
    category: "wildlife",
    duration: 5,
    groupSize: "8-12 people",
    image: "/image copy 3.png",
    tags: ["wildlife", "sunset", "photography"],
    price: 720,
    discountPrice: 600,
    monthly: 99,
    rate: 4.8,
    reviews: 980,
    quantity: 1,
  },
  {
    id: 4,
    title: "Northern Lights Expedition",
    slug: "northern-lights-expedition",
    country: "Iceland",
    category: "adventure",
    duration: 4,
    groupSize: "8-12 people",
    image: "/image copy 4.png",
    tags: ["aurora", "cold", "night sky"],
    price: 650,
    discountPrice: 500,
    monthly: 99,
    rate: 4.7,
    reviews: 1100,
    quantity: 1,
  },
  {
    id: 5,
    title: "Cherry Blossom Festival",
    slug: "cherry-blossom-festival",
    country: "Japan",
    category: "cultural",
    duration: 6,
    groupSize: "8-12 people",
    image: "/image copy 5.png",
    tags: ["flowers", "culture", "spring"],
    price: 580,
    discountPrice: 450,
    monthly: 99,
    rate: 4.5,
    reviews: 890,
    quantity: 1,
  },
  {
    id: 6,
    title: "Great Wall Hiking Tour",
    slug: "great-wall-hiking-tour",
    country: "China",
    category: "historical",
    duration: 3,
    groupSize: "8-12 people",
    image: "/image.png",
    tags: ["hiking", "ancient", "views"],
    price: 400,
    discountPrice: 320,
    monthly: 99,
    rate: 4.4,
    reviews: 700,
    quantity: 1,
  },
  {
    id: 7,
    title: "Santorini Sunset Cruise",
    slug: "santorini-sunset-cruise",
    country: "Greece",
    category: "romantic",
    duration: 2,
    groupSize: "8-12 people",
    image: "/image copy 2.png",
    tags: ["sunset", "sea", "romance"],
    price: 300,
    discountPrice: 250,
    monthly: 99,
    rate: 4.9,
    reviews: 1350,
    quantity: 1,
  },
  {
    id: 8,
    title: "Amazon Rainforest Expedition",
    slug: "amazon-rainforest-expedition",
    country: "Brazil",
    category: "nature",
    duration: 8,
    groupSize: "8-12 people",
    image: "/image copy 5.png",
    tags: ["jungle", "wildlife", "river"],
    price: 790,
    discountPrice: 640,
    monthly: 99,
    rate: 4.3,
    reviews: 620,
    quantity: 1,
  },
  {
    id: 9,
    title: "Sahara Desert Caravan",
    slug: "sahara-desert-caravan",
    country: "Morocco",
    category: "desert adventure",
    duration: 5,
    groupSize: "8-12 people",
    image: "/image copy 2.png",
    tags: ["desert", "camels", "stars"],
    price: 500,
    discountPrice: 410,
    monthly: 99,
    rate: 4.6,
    reviews: 910,
    quantity: 1,
  },
  {
    id: 10,
    title: "Swiss Alps Ski Retreat",
    slug: "swiss-alps-ski-retreat",
    country: "Switzerland",
    category: "sports",
    duration: 6,
    groupSize: "8-12 people",
    image: "/image.png",
    tags: ["ski", "snow", "mountains"],
    price: 880,
    discountPrice: 700,
    monthly: 99,
    rate: 4.9,
    reviews: 1150,
    quantity: 1,
  },
  {
    id: 11,
    title: "Petra Ancient City Tour",
    slug: "petra-ancient-city-tour",
    country: "Jordan",
    category: "historical",
    duration: 4,
    groupSize: "8-12 people",
    image: "/image copy 5.png",
    tags: ["ruins", "desert", "explore"],
    price: 480,
    discountPrice: 360,
    monthly: 99,
    rate: 4.5,
    reviews: 770,
    quantity: 1,
  },
];
